FROM node:14.17.1

WORKDIR /home/app

COPY package.json /home/app

COPY tsconfig.json /home/app

COPY src /home/app/src

RUN npm install

RUN npm run chia-client-install

EXPOSE 3000

CMD ["npm", "run", "devServer"]




