FROM node:14.17.1
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
RUN npm run chia-client-install
RUN npm run build

## this is stage two , where the app actually runs
FROM node:14.17.1
WORKDIR /app
COPY package.json ./
RUN npm install --only=production
RUN npm run chia-client-install
COPY --from=0 /app/dist .
RUN npm install pm2 -g
EXPOSE 3000
CMD ["pm2-runtime","index.js"]